title: "马列毛著作在线书库"
description: "一个收录马克思、恩格斯、列宁、斯大林、毛泽东等经典著作的在线阅读网站"
theme: jekyll-theme-cayman

# 作者信息
author: "人民书库项目"
email: "your-email@example.com"

# 网站链接（部署成功后可以改成真实网址）
url: "https://你的用户名.github.io/mlm-library"

# 导航栏设置（可选）
# 你可以在这里放置固定页面（比如 书单 / 关于）
navbar:
  - name: "首页"
    link: "/"
  - name: "书单"
    link: "/books"
  - name: "关于本站"
    link: "/about"

# 站点参数（可选）
markdown: kramdown
